### ISSUE TITLE
Missing instructions for running ClientRunnerIT

### ISSUE THREAD

**Issue by elsonrodriguez** [Hakky54/mutual-tls-ssl#8]
I'm unfamiliar with Java, Springboot, and Maven, so I couldn't quite figure out how to just run the client without running the rest of it (via `mvn clean verify`).

Would it be possible to provide a command line example? Or to make it so that `mvn spring-boot:run` starts the client?

Thank you!

**Comment by Hakky54** [comment]
Hi Elson, 

Thank you for your feedback. Yes it is possible to just only run the client. I just pushed new code which gives you the option to enable or disable it. It is now also described in the readme file.

What you need to do is run the following command: `mvn clean verify -P\!start-server` or `mvn clean verify -P!start-server`

`mvn clean verify` will still start the server because it is enabled by default. With the command above you can disable starting the server. Let me know if it works for you.

**Comment by elsonrodriguez** [comment]
Sweet, that works. Thank you!

**Comment by Hakky54** [comment]
Hi @elsonrodriguez 

I refactored the previous setup, because it took a lot of time. It was also running the unit tests. So the instruction what I gave you earlier is not available anymore. 

Now you can just run the client with the following command: `cd client/ && mvn exec:java`
