### ISSUE TITLE
An explicit instructions which tell how I can run ClientRunnerIT would be beneficial.

### ISSUE THREAD

**Issue by hisashiyamaguchi** [Hakky54/mutual-tls-ssl#85]
I'm trying to run ClinetRunnerIT with TLS mode, and have modified client/src/main/java/nl/altindag/client/Constants.java and been trying to rebuild&run, but it seems the changes has not been affected.

`private static final String DEFAULT_SERVER_URL = "https://localhost:8443";`

I have done `mvn -pl shared-server-resources clean install` after changing Constants.java, and been trying `mvn exec:java` on the client directory. As I'm not an expert of Maven, if the explicit instructions are RM, that would be beneficial for me. Here comes the error log.

https://gist.github.com/hisashiyamaguchi/d85210177d06587600542a399a87e954

**Comment by Hakky54** [comment]
It looks like you have correctly adjusted the server url. But your error message is saying it is trying to connect to `localhost:8080` and it is trowing an exception because the server is not live at that location. I think the cause is that the `mvn exec` is running the client project based on the old data from the target directory of the client. 

So to rebuild your target directory executing `mvn -pl client package` from the root directory should do the trick. Afterwords you can run `mvn exec:java` from the client directory.

Meanwhile I will try to find a more easy way to run the client as it can be indeed a bit challenging when your not familiar with Maven. 

The easy way is actually clicking on the green button within your [Intellij Idea](https://www.jetbrains.com/idea/), if you are using that one... See below for the screenshot. If you run it this way you don't need to rebuild your client module with `mvn package`
<img width="1016" alt="Screenshot 2021-02-23 at 22 36 43" src="https://user-images.githubusercontent.com/16032204/108911810-0df71c80-7628-11eb-95bb-a76e8144d088.png">

**Comment by Hakky54** [comment]
@hisashiyamaguchi 
Did you make any progress on it? Would you like any help?

**Comment by Hakky54** [comment]
Closing issue as there is no response from @hisashiyamaguchi
